"""Shared test fixtures."""

import pytest
import pandas as pd
import numpy as np


@pytest.fixture
def sample_df():
    """10-product sample DataFrame matching the unified schema."""
    return pd.DataFrame([
        {"product_id": "P001", "product_name": "Nike Running Shoes Black", "department": "Fashion", "category": "Footwear", "subcategory": "Running Shoes", "product_type": "Performance Running", "description": "High-performance running shoes", "features": "Breathable mesh, Cushioned sole", "price": 5999.0, "rating": 4.5, "reviews_count": 250, "tags": "sports, fitness", "color": "Black", "size_range": "6-13", "material": "Mesh, Rubber", "brand": "Nike", "stock_status": "In Stock", "keywords": "running shoes", "enriched_description": "Nike Running Shoes are engineered for athletes."},
        {"product_id": "P002", "product_name": "Blue Cotton Office Shirt", "department": "Fashion", "category": "Clothing", "subcategory": "Men's Formal", "product_type": "Formal Shirt", "description": "Professional office shirt", "features": "Wrinkle-resistant, Breathable", "price": 1299.0, "rating": 4.2, "reviews_count": 120, "tags": "formal, office", "color": "Blue", "size_range": "S-XL", "material": "Cotton", "brand": "Peter England", "stock_status": "In Stock", "keywords": "office shirt", "enriched_description": "Professional business shirt for corporate settings."},
        {"product_id": "P003", "product_name": "Leather Wallet Brown", "department": "Fashion", "category": "Accessories", "subcategory": "Wallets", "product_type": "Men's Wallet", "description": "Premium leather wallet", "features": "RFID protection, Card slots", "price": 899.0, "rating": 4.3, "reviews_count": 450, "tags": "wallet, leather", "color": "Brown", "size_range": "One Size", "material": "Leather", "brand": "Fossil", "stock_status": "In Stock", "keywords": "leather wallet", "enriched_description": "Premium leather wallet with RFID protection."},
        {"product_id": "P004", "product_name": "Samsung 65 inch QLED TV", "department": "Electronics", "category": "Home Electronics", "subcategory": "Television", "product_type": "Smart TV", "description": "Ultra HD smart TV", "features": "4K, HDR, WiFi", "price": 89999.0, "rating": 4.6, "reviews_count": 890, "tags": "tv, smart", "color": "Black", "size_range": "65 inch", "material": "Glass, Aluminum", "brand": "Samsung", "stock_status": "In Stock", "keywords": "smart tv", "enriched_description": "Samsung QLED TV with 4K and smart features."},
        {"product_id": "P005", "product_name": "Bosch Washing Machine 7kg", "department": "Home & Garden", "category": "Appliances", "subcategory": "Washing Machines", "product_type": "Automatic", "description": "Front-load washing machine", "features": "Energy-efficient, 7kg", "price": 24999.0, "rating": 4.4, "reviews_count": 320, "tags": "appliances, laundry", "color": "White", "size_range": "Standard", "material": "Steel", "brand": "Bosch", "stock_status": "In Stock", "keywords": "washing machine", "enriched_description": "Bosch automatic washing machine for household laundry."},
        {"product_id": "P006", "product_name": "Kindle E-Reader White", "department": "Electronics", "category": "Digital Devices", "subcategory": "E-Readers", "product_type": "E-Reader", "description": "E-reader with high-res display", "features": "Waterproof, Long battery", "price": 12999.0, "rating": 4.7, "reviews_count": 1200, "tags": "reading, books", "color": "White", "size_range": "One Size", "material": "Plastic", "brand": "Amazon", "stock_status": "In Stock", "keywords": "kindle reader", "enriched_description": "Kindle E-Reader for book lovers with weeks of battery."},
        {"product_id": "P007", "product_name": "Running Track Pants Black", "department": "Fashion", "category": "Clothing", "subcategory": "Sports Wear", "product_type": "Track Pants", "description": "Athletic track pants", "features": "Moisture-wicking, Lightweight", "price": 1899.0, "rating": 4.1, "reviews_count": 280, "tags": "sports, fitness", "color": "Black", "size_range": "S-XL", "material": "Polyester", "brand": "Adidas", "stock_status": "In Stock", "keywords": "track pants", "enriched_description": "Comfortable athletic track pants for fitness."},
        {"product_id": "P008", "product_name": "Kitchen Knife Set Steel", "department": "Home & Garden", "category": "Kitchen", "subcategory": "Cutlery", "product_type": "Knife Set", "description": "Professional kitchen knives", "features": "Stainless steel, Ergonomic", "price": 2999.0, "rating": 4.5, "reviews_count": 150, "tags": "kitchen, cooking", "color": "Silver", "size_range": "Standard", "material": "Stainless Steel", "brand": "Prestige", "stock_status": "In Stock", "keywords": "knife set", "enriched_description": "Professional kitchen knife set with ergonomic handles."},
        {"product_id": "P009", "product_name": "Yoga Mat Non-Slip Brown", "department": "Sports", "category": "Fitness Equipment", "subcategory": "Yoga", "product_type": "Yoga Mat", "description": "Non-slip yoga mat", "features": "Eco-friendly, Extra thick", "price": 899.0, "rating": 4.3, "reviews_count": 420, "tags": "yoga, fitness", "color": "Brown", "size_range": "Standard", "material": "TPE", "brand": "AmazonBasics", "stock_status": "In Stock", "keywords": "yoga mat", "enriched_description": "High-quality yoga mat with non-slip surface."},
        {"product_id": "P010", "product_name": "Canon DSLR Camera 24MP", "department": "Electronics", "category": "Cameras", "subcategory": "Digital Cameras", "product_type": "DSLR", "description": "Professional DSLR camera", "features": "24MP, 4K video, Autofocus", "price": 54999.0, "rating": 4.6, "reviews_count": 680, "tags": "photography, camera", "color": "Black", "size_range": "Standard", "material": "Aluminum", "brand": "Canon", "stock_status": "In Stock", "keywords": "dslr camera", "enriched_description": "Canon DSLR for photography enthusiasts and professionals."},
    ])


@pytest.fixture
def sample_embeddings():
    """Random 384-dim embeddings for 10 products."""
    np.random.seed(42)
    return np.random.randn(10, 384).astype(np.float32)
